### ISSUE TITLE
known issue: automatic linking to event registration?

### ISSUE THREAD

**Issue by danaskallman** [christianwach/civicrm-event-organiser#1]
On the readme file there is a reference to automatic linking to event registration being a known issue. Curious on what is needed to be done to allow for an event by event option to display the registration button if the event needs registration enabled?

**Comment by christianwach** [comment]
It's a feature that is partly written, Dana, which is why I flagged it. You
can select the registration option in the back end, but the front end code
needs writing. I'd recommend a custom template, though there is a hook in
Event Organiser that can be used to insert the link to the Civi
registration page as well. It's one of the reasons I didn't release this
plugin on the WordPress repo along with the others. Unfortunately my work
machine died yesterday, so I will have to get back to you in more detail
when it's fixed.

**Comment by christianwach** [comment]
@danaskallman I've had a (rather belated) go at [implementing this to some degree](https://github.com/christianwach/civicrm-event-organiser/blob/master/civicrm-event-organiser-functions.php).

The biggest issue that is still unclear to me is that the "registration enabled" flag in Civi is set per CiviEvent, whilst in WP it is set per EO event. This means that there isn't true sync between Civi and EO in this regard, because there may be multiple CiviEvents per EO event. This is unavoidable at present because Civi doesn't store the repeating schedule in a single CiviEvent, but instead creates individual "child" events and then discards the repeating schedule.

One option would be to migrate the "registration enabled" flag to EO event *occurrences* but since there's no UI for managing an individual occurrence, it would massively complicate the metabox on EO event edit screens.

Do you or @kcristiano have any thoughts on this?

**Comment by kcristiano** [comment]
@christianwach I've just taken a look at this and see that once enabled, we could use an action hook in the theme to display the link.

However, I cannot get the online registration checkbox to work.   Do we have an oddity on our test site or is this an issue as well?

**Comment by christianwach** [comment]
Hi @kcristiano the checkbox may be non-functional - I'll check when I get back to the UK tomorrow

**Comment by danaskallman** [comment]
Well that explains a lot ;)

Thanks @christianwach

**Comment by danaskallman** [comment]
We were testing on Civi4.6 and registration link wasn't working, but all seemed to work well on 4.7. Does that seem accurate?

**Comment by kcristiano** [comment]
Oddly, On 4.7.10 the checkbox does not change it's state - but it seems to work.  I do get a register link now.

However, if I create an event in EO and sync to CiviCRM the profile is not visible.  I have to edit the Civi Event to fix this.   Can you reproduce?   Not sure why this occurs.  CiviCRM --> EO works as expected.  EO--> Civi is where we hit issues.

**Comment by christianwach** [comment]
Sorry for the delay in getting round to this @danaskallman @kcristiano 

* Commit a1e4db9638f02852f255fbbe0b0530f9b8505e33 should solve the checkbox state.
* Commit b93c231df398e56c351a23cc267951cc77a3de24 automatically shows the Register link in in the event meta list for an event in Event Organiser 2.12.5 or greater. If you want to change the location of the link, use `remove_action( 'eventorganiser_additional_event_meta', 'civicrm_event_organiser_registration_link' );` and call the function directly in your template file.

Looking at the code, however, be careful with registration if you're using repeating events - there's no proper correspondence between Event Organiser occurrences and the CiviCRM Events that are matched to those occurrences. This plugin will always choose the URL of the first CiviEvent in the sequence. Repeating events are still very much in the early stages of development, so I'd recommend sticking to 1-to-1 correspondences if you require registration.

**Comment by kcristiano** [comment]
> This plugin will always choose the URL of the first CiviEvent in the sequence. Repeating events >are still very much in the early stages of development, so I'd recommend sticking to 1-to-1 >correspondences if you require registration.

Thanks.  I agree and will keep that in mind

**Comment by christianwach** [comment]
> We were testing on Civi4.6 and registration link wasn't working, but all seemed to work well on 4.7. Does that seem accurate?

Works for me on both Civi 4.6.21 and 4.7.11 with the latest commits @danaskallman - can you confirm?

**Comment by danaskallman** [comment]
Yeah, this is working. Thanks @christianwach
