### ISSUE TITLE
Can Event Category be required if this plugin is active?

### ISSUE THREAD

**Issue by danaskallman** [christianwach/civicrm-event-organiser#18]
Without selecting an Event Category the `Sync this event with CiviCRM` doesn't appear, meaning it isn't an option. By making this a required field an Event Category is always selected that maps to the Event Type in CiviCRM, which is required field in CiviEvent. Is this possible?

It's come up a few times during training and answering support tickets, so thought I'd ask to see if it's possible.

**Comment by christianwach** [comment]
@danaskallman I don't quite follow - it is *because an Event category is required* that the `Sync this event with CiviCRM` option is not available until one has been assigned to the Event. This can be done by using "Save as Draft" if you don't want to publish the Event.

On a broader note, the reason that `Sync this event with CiviCRM` needs to be used selectively is that I encourage the finalisation of the EO Event *before* syncing to CiviCRM - because the sync procedure is fairly robust but has its limitations... for example, when there are lots of repeating events and the schedule changes then lots of CiviEvents will be be created and deleted depending on the complexity of the schedule. This *may* lead to issues with the correspondences between an EO Event and the many CiviEvents that are mapped to its occurrences.

**Comment by danaskallman** [comment]
> it is because an Event category is required that the Sync this event with CiviCRM option is not available until one has been assigned to the Event. This can be done by using "Save as Draft" if you don't want to publish the Event.

Yeah, either way the event needs to be published or saved as draft. But if you publish or save as draft without an Event category selected, the `Sync this event with CiviCRM` still doesn't appear. At least in the times I've used it. Am I missing something? 

I am just thinking a user will never know that an event category is required for sync if it's not required for them to select it. But I get that it's a complex sync procedure and the event details should be completed in EO first correctly and not sure how that can be guaranteed by the user creating the event.

**Comment by christianwach** [comment]
@danaskallman I've filtered the Category metabox so that the default category (as defined on the admin screen) is applied to EO Events where no category has been set. Do the latest commits solve the issue for you?

**Comment by danaskallman** [comment]
@christianwach that's an interesting a approach. Lets see how it goes and yeah that seems to work in general.

**Comment by christianwach** [comment]
@danaskallman To be fair, it's probably the way things should have worked in the first place - so thank you for prompting me to put the pieces together.
