### ISSUE TITLE
Adding registration link to a button

### ISSUE THREAD

**Issue by marzast** [christianwach/civicrm-event-organiser#20]
Hi,

I'm trying to add a registration link to a button in the event organiser template:

` 
<div class="btn">
   <a href="#" class="button-6">Register</a>
</div>
`

How can I get the link address?

**Comment by christianwach** [comment]
The two functions in [this file](https://github.com/christianwach/civicrm-event-organiser/blob/master/includes/civicrm-event-organiser-functions.php) should help you.

**Comment by marzast** [comment]
Hi,

Thanks for quick reply.  I was trying to use the mentioned functions before but after some debugging I realised that the event needs to have the registration dates specified - otherwise it treats the registration as closed and exits the loop in line 118:

		if ( $plugin->civi->is_registration_closed( $civi_event ) ) continue;

Thanks,

**Comment by christianwach** [comment]
@marzast Ah yes, that's true. The plugin should probably treat empty registration dates as `NOW()` and `event_start_date` respectively, however there is [this filter](https://github.com/christianwach/civicrm-event-organiser/blob/master/includes/civicrm-event-organiser-civi.php#L2048-L2061) which allows you to override what the plugin does by default.

**Comment by christianwach** [comment]
@marzast FYI, I have slightly changed the logic in `is_registration_closed()` to match how CiviCRM itself parses the registration start and end dates (plus event end date) of a CiviEvent in order to determine a valid registration window.

You should now find that events with no Registration Dates set show the "Register" button from when an event is published and enabled until the event ends *unless* a Registration End Date has been set that is after the event End Date - in which case registration is considered open until after the specified Registration End Date has passed.

The Registration Start Date filter is still in place in case people are using it and I've added matching one so that Registration End Date can also be filtered if need be.
