### ISSUE TITLE
civi-eo acf custom field

### ISSUE THREAD

**Issue by 1pix** [christianwach/civicrm-event-organiser#26]
Hi @christianwach ,

First thank you for your great plugins allowing us to work between civi and wp more easily and smoothly :)

I wonder If you have a tips to solve my problem.
I'm stuck since two days trying to catch a "civi custom_field value", passed/sync to an event organizer, during the first sync/create operation. Unfortunatly, the meta value passed to the EO event (with the help of your "CiviCRM ACF Integration" plugin), seems not yet available at that moment..

Basically, when I create a new "civi event", I choose an option in a custom_field of type "select" (called "my-wp-event-model"), that is sync with EO event in a acf field called `modelID`.

I would like to be able to use that value during the creation/sync of the newly EO event, using a hook like `acf/save_post` or `eventorganiser_created_event` or even `civicrm_post`.
The goal is to set some default values to the newly created EO-event, based on a custom post id (the ModelID). 

This is my exemple with acf/save_post 
```php
add_action('acf/save_post', function ($post_id)
{
 $post_type = get_post_type($post_id);

    // If this isn't a 'event' post, don't update it.
    if ("event" != $post_type) {
        return;
    }

  // Check if post has already custom taxonomy terms of type "display"
  $hasDisplay = get_the_terms($post_id, 'ct_display');

  // if post already have terms of type "display", don't update it.
  if ($hasDisplay) { 
     return;
  }

  // So: Get acf field, sync between civi custom_field and wp acf_field
  $modelId = get_field('modeleID', $post_id); // THIS IS WERE META IS EMPTY

    $term_obj_list = get_the_terms($modelId, 'ct_display');
    $terms_string = $term_obj_list ? join(', ', wp_list_pluck($term_obj_list, 'name')) : '';

    // Set terms to current event
    wp_set_object_terms($post_id, $terms_string, 'ct_display');

  }
}, 20, 1);
```

I also tried to get the value dircetly from the civi custom_field, for exemple to register in a temporary post_meta and us it later, but `civicrm_post` or `pre` don't let me acces that value at that moment..
```php
add_action('civicrm_post', function ($op, $objectName, $objectId, $objectRef) {
   if($op !== 'create'){
    return;
    }

    $modelID = \CRM_Core_BAO_CustomField::getCustomFieldID('Wp_Event_Model', 'Event_Lib');
    $params = array('entityID' => $objectId, 'custom_' . $modelID => 1);
    $modelIdValues = \CRM_Core_BAO_CustomValueTable::getValues($params);
    var_dump($modelID, $modelIdValues, $op, $objectName, $objectId, $objectRef);
   // MODELidVALUES IS EMPTY .. 
    die();
}, 10, 4);
```
Civi doc say :
> you can't retrieve custom field values in the 'create' operation in the _pre and _post hooks, because the custom field values haven't been stored yet.. @see https://docs.civicrm.org/dev/en/latest/extensions/civix/#accessing-custom-fields

Any ideas or tips ?
Sorry for my very poor english explanation (i'm french),
Cheers,
Sylvain

**Comment by christianwach** [comment]
@1pix Hi Sylvain, before I try and answer, am I right in thinking that you want to do the following?

1. Create an Event in CiviCRM
2. While creating, you set a Custom Field on that Event to some value
3. Intercept the EO Event being created
4. Assign a term based on the value of the Custom Field in step 2

Cheers, Christian

**Comment by 1pix** [comment]
@christianwach Hi Christian, that's exactly that.
The value assigned in step 2 is in fact the ID of a wp post, used as a reference to get some fields value.
In my exemple i just try to get some terms et assign them (yet that would be very nice), but we will probably assign other values coming from that reference post ID (like featured image, images galery, acf repeater, etc.) 
Thanks for your help !
Cheers, Sylvain

**Comment by christianwach** [comment]
@1pix You need a hook that fires *after* the ACF Field on the EO Event has been populated. There are hooks in CiviCRM, CiviCRM ACF Integration and ACF:

* `civicrm_custom` fires after set of CiviCRM Custom Fields has been saved
* `civicrm_acf_integration_mapper_custom_edited` fires just after `civicrm_custom` fires
* `acf/update_value` fires just before an ACF Field is saved

Be careful however, because the CiviCRM docs are not quite accurate about the order in which hooks fire: for Contacts, [`civicrm_pre` fires](https://github.com/civicrm/civicrm-core/blob/master/CRM/Contact/BAO/Contact.php#L270-L277), then Custom Fields are saved and [`civicrm_custom` fires](https://github.com/civicrm/civicrm-core/blob/master/CRM/Contact/BAO/Contact.php#L384), and lastly [`civicrm_post` fires](https://github.com/civicrm/civicrm-core/blob/master/CRM/Contact/BAO/Contact.php#L399-L406). This is annoying for reasons I won't go into here!

However, this isn't the case for Events, where [`civicrm_pre` fires](https://github.com/civicrm/civicrm-core/blob/master/CRM/Event/BAO/Event.php#L71-L79), then [`civicrm_post` fires](https://github.com/civicrm/civicrm-core/blob/master/CRM/Event/BAO/Event.php#L86-L91) and lastly [`civicrm_custom` fires](https://github.com/civicrm/civicrm-core/blob/master/CRM/Event/BAO/Event.php#L150-L154). This is useful for us because we now know that the EO Event has been created when `civicrm_custom` fires.

CiviCRM ACF Integration uses the `civicrm_custom` hook to listen for updates to sets of CiviCRM Custom Fields and then saves the data to the ACF Fields that are mapped to the CiviCRM Custom Fields in that set. When creating Events individually via the CiviCRM UI, this plugin (i.e. CiviCRM Event Organiser) does not need to do this task because it is already handled by CiviCRM ACF Integration. It only needs to do that when CiviCRM ACF Integration's "Manual Sync" process runs.

Thankfully we can avoid all that complexity if we use a hook provided by ACF. So let's use the `acf/update_value/name=modeleID` hook [as per the ACF docs](https://www.advancedcustomfields.com/resources/acf-update_value/) because that's what ACF fires just before the Field you are interested in is saved.

```php
add_filter( 'acf/update_value/name=modeleID', 'my_custom_field_updated', 10, 3 );
function my_custom_field_updated( $value, $post_id, $field ) {

	// Do something with the value of your field.

	// Return the unchanged value.
	return $value;

}
```

There is only one thing to be aware of now: if the code that you write in the above function modifies the EO Event itself (e.g. by calling `eo_update_event()` to save it) then you have to remove (and re-add) the hooks that listen for those updates in this plugin and in CiviCRM ACF Integration otherwise you will create an endless loop. If you are only assigning a term to the EO Event then this won't be necessary.

Cheers, Christian

**Comment by 1pix** [comment]
@christianwach , Waow, you're amazing.
I was digging and reading your code and saw those different hooks in CIVI-ACF, I tried some of them but couldn't really understand the order and priorities of those processes.. indeed a bit complex :) But that seems christal clear now, thank you very much for your time and the nice explanation !
I will try that and give you a feedback asap.
Cheers, Stay safe, Sylvain

**Comment by christianwach** [comment]
FWIW if you _do want to save the EO Event_ in the above code, then use something like the following to remove and re-add the hooks that listen for changes on the WordPress side of things:

```php
// Grab references to the plugins.
$cai = civicrm_acf_integration();
$ceo = civicrm_eo();

// Remove WordPress callbacks to prevent recursion.
$cai->mapper->hooks_wordpress_remove();
remove_action( 'wp_insert_post', [ $ceo->eo, 'insert_post' ], 10 );
remove_action( 'eventorganiser_save_event', [ $ceo->eo, 'intercept_save_event' ], 10 );

// Do your thing...

// Reinstate WordPress callbacks in case they are needed later.
add_action( 'wp_insert_post', [ $ceo->eo, 'insert_post' ], 10, 2 );
add_action( 'eventorganiser_save_event', [ $ceo->eo, 'intercept_save_event' ], 10, 1 );
$cai->mapper->hooks_wordpress_add();

// Return the unchanged value.
return $value;
```

Hope that helps.

**Comment by 1pix** [comment]
Thank you, I saw you do that in the update_event() process in CIVI_EO (very well commented :) 
Many hanks for the snippet, really apreciate.

**Comment by 1pix** [comment]
Hi @christianwach ,
FYI, It's perfectly working with `acf/update_value` hook, thank you so much for your help.
I keep the full `eo_update_event()` process with remove/re-add hooks to avoid infinite loop aside if needed ;)

**Comment by christianwach** [comment]
@1pix Thanks for letting me know 👍

**Comment by christianwach** [comment]
@1pix Oh, just to say: try and make sure you keep CAI and CEO up-to-date from the repos here on GitHub - I'm refining the ACF integration at the moment and some recent updates require both plugins to be on the latest commit. Either that, or wait for me to push tags to each and download thos as "releases".

Cheers, Christian
