### ISSUE TITLE
Feature request : ACF field "event_id"  (like "contact_id" in wp-civi-profile-sync)

### ISSUE THREAD

**Issue by jbonlinea** [christianwach/civicrm-event-organiser#35]
Hi there, 

I've been using this plug-in extensively and so far so good.

I do thow now feel the need to have and ACF Field which would contain the civi-event-id.
This field would be exactly like the contact_id field in wp-civi-profile-sync, just a non-editable field that contain the Civi-event ID. 
It could even be a hidden field.

The idea is to easily get this value in a form (not acfe, this time)
If you want, I could develop why I do feel this need.

I have few idea of workaround, but they are a pain in the a** to set up and might not be resilient.
(basically get the value from the meta key `_civi_eo_civicrm_events`)

I guess, having a event id field would make things much easier and resilient ! 

Cheers

**Comment by christianwach** [comment]
This has been [available since 0.7.3](https://github.com/christianwach/civicrm-event-organiser/blob/88a2c45dffb5f0dc71fb5a35db95b16f7e98b0cb/includes/compat/acf/fields/class-acf-field-civicrm-event-id.php#L20). The only limitation is that the field is best used when there is a 1-to-1 relationship between events.
